server:
  port: 8091
  servlet:
    context-path: /revice-commerce/mind-order-service
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
logging:
  level:
    root: info
  config: classpath:log4j-spring.xml
#  org.springframework.data: debug
spring:
  application:
    name: mind-order-service
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER-CLASS-NAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    username: ${SPRING_DATASOURCE_USERNAME:}
    url: ${SPRING_DATASOURCE_URL:}
    hikari:
      connectionTimeout: 30000
      idleTimeout: 100000
      maxLifetime: 900000
      maximum-pool-size: 20
      minimum-idle: 10
    initialization-mode: never
  messages:
    basename: static/i18n/message
    encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        default_schema: omega_buy
    open-in-view: false
    show-sql: true
  banner:
    location: classpath:banner.txt
  main:
    banner-mode: log
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWKS_ENDPOINT:}